In [2]:
from smackbang.matches import get_matches

In [3]:
origin_one = 'NRT'
origin_two = 'SYD'
depature_date = '01/04/2022'
return_date = ""
continent = "AS"
currency = "USD"

df = get_matches(origin_one,origin_two,depature_date,return_date,currency,continent)

In [4]:
df

                  price       duration  ... combined_duration        lat         lon
cityFrom         Sydney Tokyo   Sydney  ...
cityTo                                  ...
Bangkok             349   410     9.83  ...             16.33  13.681100  100.747002
Hanoi               387   438     18.0  ...             24.33  21.221201  105.806999
Phuket City         325   502      9.5  ...             18.58        NaN         NaN
Kuala Lumpur        290   538     8.83  ...              23.5   2.745580  101.709999
Osaka               743    96    12.33  ...             13.83  34.785500  135.438004
Fukuoka             739   129    13.08  ...             15.16  33.585899  130.451004
Nagoya              773   104    23.33  ...             24.66        NaN         NaN
Taipei              453   428     19.0  ...             22.67  25.077700  121.233002
Singapore           269   628     8.25  ...              15.5   1.350190  103.994003
Ho Chi Minh City    461   444     8.92  ...              18.0  10.818800  106.652000
Okinawa Island      812   102    16.33  ...             19.25        NaN         NaN
Chiang Mai          498   504    23.83  ...             34.41  18.766800   98.962601
Seoul               731   278    22.67  ...             25.17  37.558300  126.791000
Jakarta             515   500    19.08  ...             29.83  -6.125570  106.655998
Manila              476   542     8.33  ...             13.33  14.508600  121.019997
Dhaka               577   472    34.08  ...             55.33  23.843347   90.397783
Kolkata             618   449    36.08  ...             52.33  22.654699   88.446701
Phnom Penh          561   551    11.83  ...             23.41  11.546600  104.844002
Cebu                533   594    21.08  ...             39.16        NaN         NaN
Chennai             662   473    32.42  ...             47.59  12.990005   80.169296

[20 rows x 18 columns]

In [ ]:
airports_df =